# Site
repository: sproogen/resume-theme
favicon: images/black-hole.ico

# Content configuration version
version: 2

# Personal info
name: George Dimopoulos
title: Astrophysicist
email: gd@gdimopoulos.eu
website: gdimopoulos.eu

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: astro_giorgos
github_username:  gdimo
# ... other social links ...

# Additional icon links
additional_links:
- title: Not a Top 10 podcast
  icon: fas fa-globe
  url: https://www.notatop10.fm/
# ... other additional links ...

# Google Analytics and Tag Manager
# ... analytics settings ...

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's George and I'm an astrophysicist with passion for supermassive black holes.

content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: PhD candidate in Astrophysics
        institute: Instituto de Estudios Astrof√≠sicos, Universidad Diego Portales
        caption: 2021 - Present, Santiago, Chile
        description: "**Topic:** Developing realistic X-ray models to investigate the close environments of Supermassive Black Holes **Advisor:** Prof. Claudio Ricci"

      - layout: left
        title: Master of Science in Astronomy and Astrophysics
        sub_title: University of Athens, National Observatory of Athens
        caption: 2017 - 2019, Athens, Greece
        description: |
          **Thesis:** Coronal properties of Sy 1 galaxies using *NuSTAR* data
          **Advisors:** Dr. Ioannis Georgantopoulos, Dr. Athanasios Akylas

      - layout: left
        title: Bachelor in Physics
        sub_title: University of Patras
        caption: 2012 - 2017, Patras, Greece
        description: |
          **Thesis:** Differential Photometry of the Ecliptic Binary GK Boo
          **Advisor:** Prof. P. E. Christopoulou
# Footer
footer_show_references: true
# references_title: References on request (Override references text)
footer_custom_message: |
  Favicon by <a href="https://www.flaticon.com/free-icons/black-hole" title="black hole icons">cah nggunung - Flaticon</a>.
# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag